version: 2

project_name: amq

builds:
  - id: amq
    main: ./cmd/amq
    binary: amq
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

brews:
  - name: amq
    repository:
      owner: avivsinai
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/avivsinai/agent-message-queue"
    description: "Agent Message Queue - file-based inter-agent messaging for Claude Code and Codex CLI"
    license: "MIT"
    test: |
      system "#{bin}/amq", "--version"
