//go:build linux

package cli

import (
	"errors"
	"os"
	"os/exec"
	"syscall"
	"testing"
	"time"

	"golang.org/x/sys/unix"
)

func stubLinuxPidfd(t *testing.T, open func(int, int) (int, error), send func(int, unix.Signal, *unix.Siginfo, int) error, poll func(int, time.Duration) (bool, error)) {
	t.Helper()
	oldOpen := linuxPidfdOpen
	oldSend := linuxPidfdSend
	oldPoll := linuxPidfdPoll
	oldClose := linuxPidfdClose
	linuxPidfdOpen = open
	linuxPidfdSend = send
	linuxPidfdPoll = poll
	linuxPidfdClose = func(int) error { return nil }
	t.Cleanup(func() {
		linuxPidfdOpen = oldOpen
		linuxPidfdSend = oldSend
		linuxPidfdPoll = oldPoll
		linuxPidfdClose = oldClose
	})
}

func useRealLinuxPidfdSender(t *testing.T) {
	t.Helper()
	oldSend := linuxPidfdSend
	linuxPidfdSend = unix.PidfdSendSignal
	t.Cleanup(func() { linuxPidfdSend = oldSend })
}

func TestTerminateWakePidfdKillsValidatedChildAndCannotSignalAfterExit(t *testing.T) {
	useRealLinuxPidfdSender(t)
	cmd := exec.Command("sleep", "30")
	if err := cmd.Start(); err != nil {
		t.Fatalf("start child: %v", err)
	}
	t.Cleanup(func() {
		_ = cmd.Process.Kill()
		_, _ = cmd.Process.Wait()
	})

	proc := inspectWakeProcessPlatform(cmd.Process.Pid)
	if !proc.Running || proc.PID != cmd.Process.Pid || proc.StartToken == "" {
		t.Fatalf("child identity was not validated: %#v", proc)
	}
	pidfd, err := linuxPidfdOpen(cmd.Process.Pid, 0)
	if err != nil {
		t.Fatalf("pidfd_open child: %v", err)
	}
	defer func() { _ = linuxPidfdClose(pidfd) }()

	if err := terminateWakePidfd(pidfd); err != nil {
		t.Fatalf("terminate child via pidfd: %v", err)
	}
	// Wait may report a normal exit when the child handles SIGTERM; pidfd
	// ESRCH below is the authoritative proof that the process is gone.
	_, _ = cmd.Process.Wait()
	if err := linuxPidfdSend(pidfd, unix.SIGTERM, nil, 0); !errors.Is(err, syscall.ESRCH) {
		t.Fatalf("signal retained pidfd after exit = %v, want ESRCH", err)
	}
}

func matchingLinuxWakeProcess(pid int, root string) wakeProcessInfo {
	return wakeProcessInfo{
		PID: pid, Running: true, StartToken: "start-1", BootID: "boot-1", Executable: "/usr/bin/amq",
		Args: []string{"/usr/bin/amq", "wake", "--root", root, "--me", "codex"},
	}
}

// A wake handles SIGTERM as a clean exit and removes its lock before the
// process is gone. When that teardown outlives the grace window, the SIGKILL
// authorization sees a missing lock. That is the consequence of the SIGTERM we
// sent, not an unknown actor: the exact pidfd exiting within the kill-confirm
// window is a successful retire, and no further signal is sent (issue #714).
func TestTerminateWakePidfdRetiresWhenLockRemovedDuringGracefulExit(t *testing.T) {
	for _, tc := range []struct {
		name     string
		teardown func(t *testing.T, root, lockPath string)
	}{
		{
			name: "lock removed",
			teardown: func(t *testing.T, _ string, lockPath string) {
				if err := os.Remove(lockPath); err != nil {
					t.Fatalf("remove lock during graceful exit: %v", err)
				}
			},
		},
		{
			name: "lock re-generated by a successor",
			teardown: func(t *testing.T, root, _ string) {
				writeWakeLockForTest(t, root, "codex", wakeLock{
					PID:          4343,
					ProcessStart: "start-2",
					BootID:       "boot-1",
					Executable:   "/usr/bin/amq",
					Generation:   "successor-generation",
				})
			},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			root := secureTempDirForTest(t)
			lockPath := writeWakeLockForTest(t, root, "codex", wakeLock{
				PID:          4242,
				ProcessStart: "start-1",
				BootID:       "boot-1",
				Executable:   "/usr/bin/amq",
				Generation:   "graceful-exit-generation",
			})
			expected := inspectWakeLock(root, "codex")

			var signals []unix.Signal
			var polls []time.Duration
			stubLinuxPidfd(
				t,
				func(int, int) (int, error) { return 77, nil },
				func(_ int, sig unix.Signal, _ *unix.Siginfo, _ int) error {
					signals = append(signals, sig)
					if sig == unix.SIGTERM {
						// The wake's clean-exit teardown runs after SIGTERM
						// lands and before the process is gone.
						tc.teardown(t, root, lockPath)
					}
					return nil
				},
				func(_ int, timeout time.Duration) (bool, error) {
					polls = append(polls, timeout)
					// Not exited within the grace window; exited within the
					// kill-confirm window.
					return len(polls) > 1, nil
				},
			)

			agentDir, err := openWakeAgentDir(root, "codex")
			if err != nil {
				t.Fatal(err)
			}
			defer func() { _ = agentDir.Close() }()

			attempted, err := terminateWakePidfdWithAuthorization(agentDir, expected, nil, true, 77)
			if err != nil {
				t.Fatalf("graceful exit past the grace window must retire, got %v", err)
			}
			if !attempted {
				t.Fatal("graceful exit retire did not report the attempted SIGTERM")
			}
			if len(signals) != 1 || signals[0] != unix.SIGTERM {
				t.Fatalf("signals = %v, want exactly one SIGTERM and no SIGKILL to a lock we no longer own", signals)
			}
			if len(polls) != 2 || polls[0] != wakeTerminateGrace || polls[1] != wakeTerminateGracefulExitConfirm {
				t.Fatalf("polls = %v, want grace then graceful-exit confirm", polls)
			}
		})
	}
}
